---
- hosts: tag_Name_m5_ig_staging
  become: true
  user: ec2-user
  vars:
    ami_id: "ami-026dea5602e368e96"
    rds_host_final: "{{ lookup('file', 'rds_host_address.txt')}}" 
  module_defaults:
    group/aws:
      region: "us-east-2"
  tasks:
  - include_vars:
      file: developer/rds-credentials.yaml 
  - name: Install packages
    package:
      name:
        - postgresql
        - python-psycopg2
  - name: Create IG role
    postgresql_user:
      login_host: "{{ rds_host_final }}" #
      login_user: postgres
      login_password: postgres
      name: "{{ image_gallery_user }}"
      password: "{{ image_gallery_pw }}"
      encrypted: yes
      db: users
      priv: ALL
      role_attr_flags: LOGIN,CREATEDB,CREATEROLE
      no_password_changes: yes
  - name: Create table for users
    postgresql_table:
      login_user: "{{ image_gallery_user }}"
      login_password: "{{ image_gallery_pw }}"
      login_host: "{{ rds_host_final }}" #
      owner: "{{ image_gallery_user }}"
      db: users
      table: users
      columns:
      - username varchar(50) primary key
      - password varchar(50)
      - fullname varchar(50)
      state: present